### ISSUE TITLE
(Probably another) Most useful JS framework question

### ISSUE THREAD

**Issue by thebailers** [tgvashworth/ama#1]
Hi Tom,

What would you says is the most used/useful JS framework currently to learn? React? Angular? Ember? Something else?

Many thanks
Simon

**Comment by tgvashworth** [comment]
Hey @thebailers — really sorry it's taken me so long to get back to you! And, given I don't know that I have a good answer, I'm probably useless to you.

With this kind of thing, I try to pick anything that seems interesting and try to reach the 'zen' of the tool by understanding _why_ it exists and how the authors use it. This kind of first-principles approach enables you to use the library and associated utilities without friction because they 'fit' into your mental model.

This is really useful when approaching another problem where the tool you learned isn't available. You can reapply the ideas in a new context.

Anyway, enough philosophy & bullshit.

As to what you should go play with right now, I think React is the best available way to build user interfaces if you value JavaScriptishness (_preeetty_ sure that's a word), a large, vibrant ecosystem and radical [simplicity](https://www.youtube.com/watch?v=rI8tNMsozo0). They've found a nice compromise between familiarity-in-use and the ideas it introduces (to front-end). In that way, I think React is your best best.

However, there are two things you absolutely should do no matter what framework you pick: learn the underlying layer, and try to build things with it. That means the [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) and plain 'ol JavaScript.

Try, for example, building a little todos app with those two, and then again with React. Try to match them up, feature for feature. The idea is to find the bits that React solves, to understand, _from experience_, why it exists and what it does for you.
